#!/bin/bash

#--------------------------------------------
#------------project maker
#--------------------------------------------

#--------------------------------------------------------
#------ bash script to knit and compile 495 project.
#--------------------------------------------------------

#---knit Rnw files using littler
	r 495knit.R

#---move tex files to /tex subdirectory
	mv *.tex tex/

#---typeset!!
	pdflatex tex/495.tex
	pdflatex tex/495.tex
#---move pdf back to home directory
#	mv tex/495.pdf .
