#!/bin/bash

#--------------------------------------------
#------------make495
#--------------------------------------------

#----------------------------------------------------------------
#------ bash script to knit, typeset, and display 495 project.
#----------------------------------------------------------------

#---knit Rnw files using littler
	r 495knit.R

#---move tex files to /tex subdirectory
	mv *.tex tex/

#---typeset!!
	pdflatex tex/495.tex
	pdflatex tex/495.tex

#---display pdf
	mupdf 495.pdf
